### ISSUE TITLE
Allow separating per-module symbols

### ISSUE THREAD

**Issue by n1k0** [esdoc/esdoc#106]
Currently, esdoc put all exported symbols at the first level of the navigation hierarchy, except if you move a module to its own subdirectory; I was expecting subsections to be created respecting the natural modularization reflected by the file system.

For example, in a project I have to move `src/utils.js` to `src/utils/index.js` in order to go from

![screen shot 2015-10-06 at 16 16 04](https://cloud.githubusercontent.com/assets/41547/10311096/9608eee8-6c45-11e5-946a-ec3cc9d6ed5b.png)

to

![screen shot 2015-10-06 at 16 06 57](https://cloud.githubusercontent.com/assets/41547/10311103/9abf0ef4-6c45-11e5-9cfd-ac92285f8a87.png)

I find it odd to have to alter one's project file organization in order to structure apidocs navigation tree; would it be reasonable to expect an option allowing to respect the natural modularization?

**Comment by h13i32maru** [comment]
This is difficult problem. Because classes are normally one per a file. So I am not using file name for navigation separater. But functions are one or plural per a file.
 
- If functions are one per a file, file name for navigation separater is wordy
  - e.g. https://github.com/ReactiveX/RxJS/tree/master/src/operators
- If functions are plural per a file, it is useful
  - e.g. https://github.com/Kinto/kinto.js/blob/master/src/utils.js

<img width="266" alt="2015-10-10 18 22 31" src="https://cloud.githubusercontent.com/assets/985170/10410560/658cc634-6f80-11e5-8e5c-015f4b19a48e.png">


after I was troubled, I chose current navigation style.


Personally, I like one default export per a file. So one class / function is one file. If you want to collect utility functions, I proposal to define Util class and use static methods.

What do you think this?

**Comment by n1k0** [comment]
The thing is, there's the concept of *module*, which is basically a collection of exported symbols, which can be classes, functions, constants, etc…; that's probably why you can `export default` and `export`… If find it really convenient to organize a codebase in modules [> submodules] > exported symbols.

Could we at least hope to eventually have an option to specify grouping, eg in `esdoc.json`?

**Comment by n1k0** [comment]
> If you want to collect utility functions, I proposal to define Util class and use static methods.

That would work, but would also defeat the whole purpose of ES6 modules imho :/

**Comment by n1k0** [comment]
Also, I don't think using subfolders to *detect* modules/namespaces is a good idea, because that means esdoc suggests — well, in that case, enforces — static conventions for organizing the code hierarchy on the filesystem… I think it should work the other way around, esdoc should only rely on the ES6 module spec to generate and reflect the code modularization in the navigation hierarchy.

**Comment by h13i32maru** [comment]
I understood your thought.

> Could we at least hope for eventually having an option to specify grouping, eg in esdoc.json?

It is not best. Because each documentations are different looks.

I regard that current navigation style is simple than your proposal. So, I can not accept your proposal.

Sorry.


- ``dir > identifier`` (I like this)

<img width="300" alt="2015-10-10 20 13 20" src="https://cloud.githubusercontent.com/assets/985170/10410888/6ed1e9c6-6f8b-11e5-9b86-e164638bd41e.png">

<img width="300" alt="2015-10-10 20 12 45" src="https://cloud.githubusercontent.com/assets/985170/10410889/72425974-6f8b-11e5-8ec0-9fabda7e033b.png">

- ``dir > file > identifier``

<img width="300" alt="2015-10-10 20 10 25" src="https://cloud.githubusercontent.com/assets/985170/10410887/6ece96cc-6f8b-11e5-91a4-d70b0dc91905.png">
<img width="300" alt="2015-10-10 20 12 08" src="https://cloud.githubusercontent.com/assets/985170/10410890/72435432-6f8b-11e5-9e04-787df8a6c0b3.png">

I suggest you to use [ESDoc API](https://esdoc.org/api.html) for your navigation style.

**Comment by n1k0** [comment]
I'll dig into the plugin API and see if I can come with something :) 

Thanks.

**Comment by h13i32maru** [comment]
You can modify HTML using ``onHandleHTML`` in plugin.

Thank you for understanding.

**Comment by crucialfelix** [comment]
I also have the same problem. I'm working on a project where everything is small composable functions. But they are all on the top level unless I move them into subdirectories.

Maybe the plugin API could offer a hook to assemble the directory index.
