### ISSUE TITLE
Add theming

### ISSUE THREAD

**Issue by jaylaw81** [esdoc/esdoc#116]
The ability to pass themes into the esdoc via CLI or config.json

**Comment by raveclassic** [comment]
@jaylaw81 AFAIK Esdoc [plugin api](https://esdoc.org/api.html) has a method `onHandleHTML` - you could use that to modify output as you need.

**Comment by h13i32maru** [comment]
@jaylaw81 Sorry, I do not plan to support multi themes. Because I think that readers confused when they are reading the documentation if multi themes are exists.

If you must want to use theme, you can use ``config.styles``, ``config.scripts``, Plugin and publisher. See [ESDoc API](https://esdoc.org/api.html) for more information.

Thanks.

**Comment by h13i32maru** [comment]
@raveclassic Thanks for reply!
