### ISSUE TITLE
Configure for non-top-level? Want to use with Nodal.

### ISSUE THREAD

**Issue by keithwhor** [esdoc/esdoc#200]
I'd be really interested in using ESDoc with Nodal: https://github.com/keithwhor/nodal

The project's picking up some steam, I've written inline documentation, but page generation is a pain in the butt. ESDoc just will not play nice. Can't use import / export because node using CommonJS require + no Babel (and it'll stay that way for a while. Don't want to introduce a build step.) I have a design pattern I use in Nodal where I have `module.exports = (function() {})();` and wrap everything an an IIFE.

Can we work together for a solution? If you point me in the right direction to modifications I'd need to make I'm more than willing to take a crack at it. I'd be interested in extending it to Nodal projects as well, so developers can document the controllers / models /etc that they write for their own internal teams.

**Comment by silkentrance** [comment]
@keithwhor I think that you are better off with other documentation systems such as jsdoc3 for your specific reimplementation of the wheel :grinning:

Reason here is that esdoc uses the AST produced by the parser to find out about types. Given your old school and very idiomatic development approach, esdoc will not be able to support that.

**Comment by h13i32maru** [comment]
@keithwhor I do not have the plan to support ``require/module.exports``. Because ESDoc is developed for ES6(class, let/const, import/export, etc...). Please wait for until supporting ``import/export`` in node.js, or using [babel modules transform](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-es2015-modules-commonjs).
