### ISSUE TITLE
Generating docs for "default export" functions

### ISSUE THREAD

**Issue by kctang** [esdoc/esdoc#254]
In a react/redux app, I have a file that exports the following:

``` javascript
// style-1
export default connect(mapStateToProps, mapDispatchToProps)(MyFunctionalStatelessComponent);
```

I can't seem to see this in the generated docs. 

However, if i change it to:

``` javascript
// style-2
const MyComponent = connect(mapStateToProps, mapDispatchToProps)(MyFunctionalStatelessComponent);
export default MyComponent;
```

`MyComponent` will be generated as a variable in the docs.

Question: Can I generate appropriate doc using `style-1`?

Guidance on this is much appreciated.

**Comment by hmil** [comment]
I believe this is a planned feature but not yet supported (see: https://github.com/esdoc/esdoc/blob/master/src/Factory/DocFactory.js#L84 )

How would you name the exported object? I'm not sure using the file name is super safe. Having an `@name` tag here could be useful, what do you think?

**Comment by andrewreedy** [comment]
:+1:

**Comment by otakustay** [comment]
@hmil This code may create a global variable `MyComponent`, it is not a good practice

**Comment by typhonrt** [comment]
@otakustay Are you sure that a global variable is created? It is my understanding that ES Modules are inherently / implicitly in strict mode.

**Comment by otakustay** [comment]
@typhonrt If this code is run in ES6 module mode, there is no global variable created, however current days it is very common to compile ES6 to ES5 with babel and run it in script mode, it can **cause ReferenceError** in strict mode or **create a global variable** in non-strict mode

**Comment by typhonrt** [comment]
@otakustay fair enough. Indeed there should be a better solution for imports (let's say functions) that are subsequently exported directly or invoked and output exported as in the [example above](https://github.com/esdoc/esdoc/issues/254#issue-142976132).

A general problem is that ESDoc is not going to do any sort of introspection of the actual function call. Also, presently exports are not notated in docs generated. 

So the only way to get it picked up without causing the problems you note in `style-1` is:
```
// style-2
const MyComponent = connect(mapStateToProps, mapDispatchToProps)(MyFunctionalStatelessComponent);
export default MyComponent;
```

A reasonable future enhancement is perhaps adding a module / file scope entry in doc generation. Imports / exports + other module specific data could be notated and displayed. Right now this is just separate generated doc items in the same directory path which is really messy with the default left-hand navigation.

For dynamic exports documentation could be added such as `@type` support picks up dynamic exports. Don't hold your breath though on this happening anytime soon. 

So, the only way to get things picked up safely in docs presently is the `style-2` method.

For the original author and others. Another interim solution which overcomes the left-hand navigation messiness is my plugin, [esdoc-plugin-enhanced-navigation](https://www.npmjs.com/package/esdoc-plugin-enhanced-navigation), as it groups multiple doc exports per file rather than in one large group per directory path. 

Besides making the left-hand navigation much prettier and functional it does group doc objects per file when multiple exist.

**Comment by h13i32maru** [comment]
I don't support `style-1` such as a unknown type exporting.
