### ISSUE TITLE
Allow src to have multiple folders

### ISSUE THREAD

**Issue by andreu86** [esdoc/esdoc#270]
I need to include more than one single src directory to generate documentation, what's the best way to do it?

**Comment by typhonrt** [comment]
You can use the `includes` config parameter. 

Set the source directory to `'.'` and then provide an includes regex for all the actual source directories like: `"includes": ["^src1/", "^src2/"]`

What this does is set the root directory to be entirely scanned, but the "includes" regex array limits the directories to only those that match.

**Comment by pizzafroide** [comment]
It would be great if, instead of `includes` and `excludes` properties, `src` property could support [globby](https://github.com/sindresorhus/globby) arrays (or similar).

**Comment by raveclassic** [comment]
I opened similar issue ago but with no luck: https://github.com/esdoc/esdoc/issues/72#issuecomment-195889544
I realy don't get why this lib uses its own file-walking algorithm instead of just collecting files through globs or (what is much easier) via plain path arrays...

**Comment by raveclassic** [comment]
@typhonrt BTW your approach is not working for me =(

**Comment by typhonrt** [comment]
Weird... I use that technique all the time as do some of my plugins. If you are including multiple roots 1 directory deep perhaps try leaving off the `/` so try:
```
{
   "source": ".",
   "destination": "docs",
   "includes": ["^src1", "^src2"]
}
```
----------------------------

Having a bit of insight into ESDoc the default left-hand source navigation is a bit wonky when it comes to supporting multiple paths. Consider that when one sets a `source` entry in an ESDoc configuration file that the left hand navigation uses that as a base directory even if it is not the root directory from where ESDoc is being run from. I can't speak for @h13i32maru, but I gather the question about why multiple source roots was not initially supported is due to the current implementation of the default left-hand navigation.

So, at least a consideration of impacted areas in upgrading ESDoc to support multiple source roots includes upgrading the default left-hand source navigation. 

Personally I think the left-hand navigation needs updating. I have a really nice plugin replacement [esdoc-plugin-enhanced-navigation](https://www.npmjs.com/package/esdoc-plugin-enhanced-navigation) for some inspiration.

**Comment by raveclassic** [comment]
@typhonrt I can accept absence of different source roots as I can easily set root to `.` but that would require complex regexp's to filter out the stuff that should not be processed. I don't get why should I mess with all those regexping when I could just pass an array of files I need to be processed.
Seems like I'm ending up with a fork.

**Comment by typhonrt** [comment]
@raveclassic  I completely agree. I'm only providing the solution that works now; not commenting on its elegance; which it lacks. If I had any say, and unfortunately I don't, I'd upgrade this right away. I'm still holding out hope for at least a little while longer that @h13i32maru will provide some forward progress, reach his vision for 1.0, then accept outside collaborators like he somewhat recently mentioned.

If your needs are fairly complex perhaps consider creating a plugin though that could create the necessary regexp includes filter based on a more coherent data added to the plugin configuration. Great solution, no, but if you have many repos that have a complicated setup you could also create a configuration file linked via GitHub or published on NPM which your plugin uses across all repos rather than setting up specific details in each repo. 

For instance my plugin [esdoc-plugin-jspm](https://www.npmjs.com/package/esdoc-plugin-jspm) automatically creates the includes regexp for all JSPM managed repos that have ESDoc configuration files (it does a lot else too!). I'll be working on `esdoc-plugin-npm` soon that does the same across all NPM modules which have valid ESDoc config files.

**Comment by raveclassic** [comment]
@typhonrt Well I'm running ESDoc from node via API so I already have such shared esdoc config module for different projects. Moreover this config depends heavily on ENV. 
If you don't mind I'd open the same PR for your fork?

**Comment by typhonrt** [comment]
I have an experimental branch of my ESDoc fork [source-globs](https://github.com/typhonjs-node-esdoc/esdoc/tree/source-globs) that seems to offer a great solution. I've include the `glob` npm module and treat `config.source` if it is an array then as an array of globs otherwise the normal processing occurs. Also if`config.test.source` is an array it also is treated as an array of globs. It should be noted that `config.source` / `config.test.source` is set to '.' in the glob loading path.

I added a basic sanity check in tests to just make sure things work, but without running a full test suite. I have tested this a separate repo and so far things work great for source and test loading.

No extra config parameter needed with this potential solution. 

You can install it via:
`npm install "git+https://git@github.com/typhonjs-node-esdoc/esdoc.git#source-globs"`

Or including the above in `package.json`.

**Comment by h13i32maru** [comment]
duplication
