### ISSUE TITLE
Node 6 compatibility

### ISSUE THREAD

**Issue by ro31337** [esdoc/esdoc#274]
Node 6 was released (!) two days ago.

And while installing I'm getting this message:

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs v3.0.0 and before will fail on node releases >= v6.0. Please update to graceful-fs@^4.0.0 as soon as possible.
```

`graceful-fs` is the part of `fs-extra`:

```
├─┬ esdoc@0.4.6
...
│ ├─┬ fs-extra@0.20.1
│ │ ├── graceful-fs@3.0.8
```

It's fixed in `fs-extra@0.30.0`, and this version has `"graceful-fs": "^4.1.2"` dependency.

So just updating `fs-extra` should be enough.

**Comment by typhonrt** [comment]
@ro31337 I'm just curious.. Does ESDoc fail on Node 6 due to this potential issue? I'm guessing not, but if so I have a [maintained fork](https://github.com/typhonjs-node-esdoc/esdoc) of ESDoc with updated dependencies including `fs-extra` and Bablyon 6 parser support.

It should be noted that with the updated dependency one still gets a warning that the update of `graceful-fs@^4.0.0` will fail on Node 7; so I'm curious if it actually causes things to fail or is a semi-benign warning.

I'm sure @h13i32maru will update all dependencies soon in a new release.

**Comment by h13i32maru** [comment]
Now, ESDoc supports Node.js v6.
