### ISSUE TITLE
Allow closure compiler's Unknown type

### ISSUE THREAD

**Issue by alexeagle** [esdoc/esdoc#282]
Closure compiler allows a `{?}` type annotation where a type is not declared at all.

https://developers.google.com/closure/compiler/docs/js-for-compiler#types

ESDoc blows up on this:

```
alexeagle-macbookpro2:tmp alexeagle$ cat esdoc.json
{ "source": "esdoc_in", "destination": "esdoc_out" }
alexeagle-macbookpro2:tmp alexeagle$ grep version node_modules/esdoc/package.json
  "version": "0.4.7"
alexeagle-macbookpro2:tmp alexeagle$ cat esdoc_in/*
export class Operator {
    /**
     * @param {function(?, number): ?} project
     * @param {?} thisArg
     */
    constructor(project, thisArg) {
        this.project = project;
        this.thisArg = thisArg;
    }
    /**
     * @param {Subscriber<?>} subscriber
     * @param {?} source
     * @return {?}
     */
    call(subscriber, source) {
        return source._subscribe(new MapSubscriber(subscriber, this.project, this.thisArg));
    }
}
alexeagle-macbookpro2:tmp alexeagle$ ./node_modules/.bin/esdoc -c esdoc.json
error: could not process the following code.
/Users/alexeagle/tmp/esdoc_in/test.js
1|     /**
2|      * @param {function(?, number): ?} project
3|      * @param {?} thisArg
4|      */
5|     constructor(project, thisArg) {

/Users/alexeagle/tmp/node_modules/esdoc/out/src/ESDoc.js:409
            throw _iteratorError5;
            ^

Error: Empty Type found name=thisArg desc=
    at Function.parseParam (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Parser/ParamParser.js:159:15)
    at MethodDoc.param (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Doc/AbstractDoc.js:575:57)
    at MethodDoc.param (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Doc/MethodDoc.js:108:72)
    at MethodDoc._apply (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Doc/AbstractDoc.js:107:21)
    at MethodDoc._apply (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Doc/MethodDoc.js:50:72)
    at MethodDoc.AbstractDoc (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Doc/AbstractDoc.js:70:10)
    at new MethodDoc (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Doc/MethodDoc.js:39:75)
    at DocFactory._createDoc (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Factory/DocFactory.js:635:14)
    at DocFactory._traverseComments (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Factory/DocFactory.js:565:24)
    at DocFactory.push (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Factory/DocFactory.js:451:22)
```

**Comment by typhonrt** [comment]
I'm writing a lot of plugins for ESDoc.. It seems that an ESDoc plugin hook could be added to:
https://github.com/esdoc/esdoc/blob/master/src/Parser/ParamParser.js#L85
such that a plugin could parse the parameters and convert them into a format that is acceptable. 

In a naive assumption in general `?` could be transformed into `*`. I tested this by adding:
`typeText = typeText.replace(/^[?]$/, '*');`
before: https://github.com/esdoc/esdoc/blob/master/src/Parser/ParamParser.js#L96

So this would allow `{?}` (and only this) to pass through and generate docs.

@h13i32maru it seems reasonable to add a plugin hook here, so take a look when possible.

**Comment by alexeagle** [comment]
Is it expected in general that Closure Compiler type annotations should
work with ESDoc? I haven't checked if there are other syntaxes that have
similar problems...

**Comment by typhonrt** [comment]
Well.. You can see the parsing performed in `parseParam`. If a ESDoc plugin hook was available you'd be able to override the limited parsing performed and fill in `result` with appropriate values supporting the Closure Compiler type annotations. Ala this would be replaced by the plugins processing: https://github.com/esdoc/esdoc/blob/master/src/Parser/ParamParser.js#L87-L149

`result` would fallback to the default processing in `parseParam` unless a loaded plugin provided an overridden `result` via a plugin hook (which doesn't currently exist). 

With the default processing `?` isn't recognized by the pattern matching. Whether ESDoc should support a thorough implementation is up to @h13i32maru, but a plugin hook would allow this to behavior to be overridden for custom behavior. 

From taking a look at the code the below fields are filed in for `result`:
```
result =
{
   nullable: `boolean | null`,
   types: `Array<string>`,
   spread: `boolean`,
   optional: `boolean`,
   defaultValue: `*`,
   defaultRaw: `{}`,
   name: `string`,
   description: `string` 
}
```

While slightly messy since ESDoc is transpiled to ES5 for the NPM module you can directly modify the `at Function.parseParam (/Users/alexeagle/tmp/node_modules/esdoc/out/src/Parser/ParamParser.js:159:15)` function to test what it would be like to perform custom parsing without an ESDoc plugin. Replace the default processing with a few test examples of parsing Closure Compiler type annotations storing data in the `result` hash and see if any progress can be made. If so then this is a reasonable candidate for an ESDoc plugin hook; I think it is, but I'm not the owner or a collaborator. 

I'd gander that supporting everything one could throw at ESDoc is a big task, so a plugin hook to customize behavior seems reasonable in this case.

As things go @h13i32maru hasn't accepted outside collaborators and the velocity is slow with ESDoc right now, so being a bit proactive and proving that a plugin hook here can solve your problem is handy. There are also several other issues related to parsing various tags/types that this could be relevant to in regard to 

I've been waiting a month for a simple PR adding more data to existing plugin hooks that @h13i32maru has not responded to... :| which is blocking some really awesome visualization plugins for graphing source code dependencies, so it is what it is right now...

**Comment by h13i32maru** [comment]
Please use `*` type and argument name in function.

The below code is valid at ESDoc v0.5
```js
export class Operator {
  /**
   * @param {function(foo:*, bar:number): *} project
   * @param {*} thisArg
   */
  constructor(project, thisArg) {
    this.project = project;
    this.thisArg = thisArg;
  }
  /**
   * @param {Subscriber<*>} subscriber
   * @param {*} source
   * @return {*}
   */
  call(subscriber, source) {
    return source._subscribe(new MapSubscriber(subscriber, this.project, this.thisArg));
  }
}
```
