### ISSUE TITLE
Combine forces with "documentationjs"

### ISSUE THREAD

**Issue by gajus** [esdoc/esdoc#284]
- @tmcw (documentationjs)
- @jfirebaugh (documentationjs)
- @h13i32maru (esdoc)

Maintaining ESDoc and https://github.com/documentationjs/documentation seems like duplication of effort. Both projects have the same aims.

JSCS [recently merged with ESLint](https://medium.com/@markelog/jscs-end-of-the-line-bc9bf0b3fdb2#.l1s9755m7). Thats a good example of productive collaboration thats going to benefit everyone. It would be nice to see ESDoc combine forces with documentationjs team.

On a related note, I think that ESDoc is a better name for the project - "documentation" is impossible to Google.

**Comment by typhonrt** [comment]
So, my take on this possibility assuming this is a general request to fold ESDoc into documentationjs is that documentationjs is substantially different in architecture such that ESDoc has a particular edge. In particular this is the plugin architecture supported in ESDoc. @h13i32maru got things right by exposing plugin hooks allowing extension of ESDoc. I took a look at documentationjs and this seems to be what I consider a [major missing feature](https://github.com/documentationjs/documentation/issues/70)

I've spent a good part of the last 2 months working on many [ESDoc plugins](https://github.com/typhonjs-node-esdoc) that greatly extend ESDoc. Given this time investment I'd really not want to move to documentationjs. Now there is a chance I missed any plugin support in documentationjs, but I couldn't find anything in documentation / API info or a cursory review of the source code.

Now where documentationjs has an edge over ESDoc is in it's [contributing](https://github.com/documentationjs/documentation/blob/master/CONTRIBUTING.md) agreement insofar that it is an "OPEN open source" project whereas ESDoc is a guarded project where @h13i32maru has not accepted outside collaborators. This is why ESDoc is slow moving and terribly frustrating to work with when PRs and issues that are easy to implement go unaddressed for months. I can only _assume_ why this is the case from language / communication issues (in general since @h13i32maru is from Japan) or @h13i32maru just being busy with other work to other external concerns. IMHO this is the only weakness of ESDoc insofar that @h13i32maru should accept outside collaborators who can reliably move forward ESDoc in his absence. 

In that regard I'd really like to be added as a collaborator for ESDoc as my vision to get to 1.0 is to add more plugin hooks and fix any important outstanding issues as necessary. By expanding the plugin hooks to ESDoc such that it allows full modification of every part of the pipeline and keeping the internal functionality more or less minimal will result in a very powerful documentation tool. Everything currently limiting with ESDoc can be solved by more plugin hooks and 1st or 3rd party plugins.

My only message to @h13i32maru is to congratulate his effort on ESDoc. Whether he intended to create a popular tool or not ESDoc has a lot going for it. Please consider that many now depend on ESDoc and some of us want to help move it forward.

**Comment by hmil** [comment]
I agree 100% with @typhonrt . ESDoc and documentationjs should coexist to provide an alternative to each other. tbh I did not like the look and feel of documentationjs and found ESDoc more intuitive. ESDoc's plugin system is well aligned with Node.js' separation of concerns philosophy.

However, ESDoc is not mature. After digging in the code for my own [pr](https://github.com/esdoc/esdoc/pull/256) it felt that the code would need some heavy refactoring and cleanup. For instance, the underlying parser should be changed to something like [babylon](https://github.com/babel/babylon) to [support edgy features like Flow](https://github.com/esdoc/esdoc/issues/55).

This means there is a lot of work to be done on this package, that and the intense comunity activity is probably too much work for a single maintainer. If @h13i32maru has a different vision or keeps being silent, a fork may be the way to go.

I have much respect for @h13i32maru and the work he's done on this package so far but there is a burning need for a powerful, flexible documentation tool for ES6 and future ES versions to come. ESDoc is the perfect base for such a tool and if someone would like to fork the project, then I'll be on board.

**Comment by typhonrt** [comment]
>If @h13i32maru has a different vision or keeps being silent, a fork may be the way to go.

Indeed.. I've been holding off inclinations to fork as I'd hate to split this community when it is so close to being _the_ powerful / flexible documentation tool we all need. I have a window of ~3 months right now where I can put in some reasonable time to get ESDoc to 1.0 and a solid official release. 

>However, ESDoc is not mature. After digging in the code for my own pr it felt that the code would need some heavy refactoring and cleanup. For instance, the underlying parser should be changed to something like babylon to support edgy features like Flow.

More or less this is prime territory of providing plugin hooks such that the parser can be changed (this is already possible) and all the internal hard coded AST processing can also be swapped out. IE [ParamParser](https://github.com/esdoc/esdoc/blob/master/src/Parser/ParamParser.js) / [CommentParser](https://github.com/esdoc/esdoc/blob/master/src/Parser/CommentParser.js) / [DocFactory](https://github.com/esdoc/esdoc/blob/master/src/Factory/DocFactory.js).  For instance a plugin hook in DocFactory could override any of the default doc processors. Likewise having a plugin callback for ParamParser would potentially allow [Closure types / TypeScript to be supported](https://github.com/esdoc/esdoc/issues/282)

I've actually had some success in simply overwriting any generated docs such as [esdoc-plugin-enhanced-navigation](https://www.npmjs.com/package/esdoc-plugin-enhanced-navigation) [ live demo / (click `JSPM Managed source to reveal` / also context click to jump to linked code on Github)](https://docs.typhonjs.io/typhonjs-demos/backbone-es6-localstorage-todos/).

And like yourself am getting frustrated that my [simple PR](https://github.com/esdoc/esdoc/pull/263) to add more data to existing plugin callbacks is simply not getting merged.  I just spent the last 5 days doing a [significant rewrite of escomplex](https://github.com/escomplex/escomplex/issues/33) for instance to support ES6 and all major parsers including babylon and in short order would like to publish [esdoc-plugin-escomplex](https://github.com/typhonjs-node-esdoc/esdoc-plugin-escomplex) to add complexity reports w/ D3 visualizations. I'm also significantly done with adding adding D3 interactive dependency graphs for NPM / JSPM packages & source code via [esdoc-plugin-dependency-graphs](https://www.npmjs.com/package/esdoc-plugin-dependency-graphs) [(live demo / JSPM packages for now / context click on nodes to jump to NPM or Github repo!)](https://docs.typhonjs.io/typhonjs-demos/backbone-parse-es6-todos-improved/graphs/jspm_packages.html). I can't support source code graphs in the latter plugin and I could easily complete both of these plugins by getting the mentioned PR accepted as I simply need the associated file name / path to be passed to the AST plugin callback!

Again I hope this comes across to @h13i32maru not as a negative as you created a good tool that almost is great. We're here to help you make it great and then some!

**Comment by h13i32maru** [comment]
@gajus @typhonrt @hmil 
Thanks for this comment!

I will properly read these comments on the weekend. However I am not very good at English. So, I think that takes a long time to read the comments. And I am required the energy to read it.

Please understand you that I do not give up ESDoc and I do not get tired of ESDoc. I have a passion for ESDoc. But now I am developing other tools and I am busy at private. So I am difficult to have time for ESDoc. I plan to return in ESDoc at June.

**Comment by ratson** [comment]
It is sad that ESDoc still an [one person](https://github.com/orgs/esdoc/people) project.
@typhonrt seems stop contributing anymore, [the fork](https://github.com/typhonjs-node-esdoc/esdoc) has been inactive for 5 months.

**Comment by typhonrt** [comment]
I'm trying to be patient and wait for @h13i32maru to finish v1.0 which will be a better point to jump off as far as a major fork is concerned; I don't see things working out with the present course of combining forces just from communication issues alone. I too am quite unhappy at this point with the long delays, but it's open source. I had my own set of external issues to deal with last ~4 months that kept me from open source efforts. It does look like there has been periodic work on ESDoc every once in a while. I really hope the author finishes his v1.0 soon.

**Comment by h13i32maru** [comment]
Sorry for late replying.

I don't want to combine with other tools.
I have my own thought of document.

And just yesterday, I released v0.5.0 that has many features.
https://esdoc.org/manual/changelog/CHANGELOG.html

In future, I will work on ESDoc on my own pace.
Please your understanding.

Thanks.

**Comment by tmcw** [comment]
👋 @h13i32maru - great work on ESDoc! I agree with the folks who said it's a good thing to have two approaches. There are a lot of interesting ideas in ESDoc and problems you've solved which are a big inspiration for documentation.js. Hopefully all of the solutions share the best ideas and code since we're all using liberal licenses, and it makes the whole ecosystem better.
