### ISSUE TITLE
Enhance Markdown links support

### ISSUE THREAD

**Issue by pizzafroide** [esdoc/esdoc#307]
It would be great to support "general" Markdown links as in:

```js
/**
 * Function related to a [link] in some way.
 */
export function foo() {}

/**
 * Another function related to the same [link].
 */
export function bar() {}

/**
 * [link]: http://seems-interesting.com
 */
```

**Comment by typhonrt** [comment]
Just my thoughts, but this is not likely to be an accepted enhancement. Separate comment blocks are parsed as Markdown independently of the whole file / document.

**Comment by pizzafroide** [comment]
Too bad! It was worth the try anyway. Here also, I'll write a plugin. :-)

**Comment by typhonrt** [comment]
Once again a good starting point as you recognized is a plugin. This works best as a plugin because it's more of an optional situation where the user knows this kind of translation will occur by including the plugin. You should be able to implement your idea by modifying the code in `onHandleCode` callback. Good luck!
