### ISSUE TITLE
Build from source errors

### ISSUE THREAD

**Issue by jakeknerr** [esdoc/esdoc#332]
When I try to build from source or run tests, many pieces of code have a '...' inserted which are throwing syntax errors.  

Is there something I am missing? Perhaps some compile step to remove or convert the ... ?

**Comment by typhonrt** [comment]
What version of Node.js are you running? It appears v6 is now required to build / run tests for ESDoc. This is a recent change over the last month. See the v1.0 [release notes](https://github.com/esdoc/esdoc/issues/293).

In particular as far as Babel is concerned instead of using the full [es2015 preset](https://babeljs.io/docs/plugins/preset-es2015/) just [transform-es2015-modules-commonjs](https://github.com/esdoc/esdoc/blob/master/.babelrc#L3) is being used with Node 6. And from [package.json](https://github.com/esdoc/esdoc/blob/master/package.json#L13) one can see the "engine" requirement.

I haven't had time to review the latest master commits by @h13i32maru. 

IMHO if Node 6 is also a runtime requirement for the lastest ESDoc (currently still unreleased on NPM) that is a debatable misstep or at least contentious regardless if v6 is imminently LTS over supporting es2015 preset transpilation which would allow ESDoc to run on older versions of Node. My opinion is that a tool like ESDoc should work across as wide of a swath of Node versions as possible including all versions that es2015 preset transpilation supports. 

If this solves your problem please close this issue.

**Comment by jakeknerr** [comment]
Thanks for the help and your time.  It didn't resolve the issues, but that's OK because we decided to use JSDoc for documentation instead.  Thanks again.
