### ISSUE TITLE
Problem with DocBuilder.js or esdoc-es7-plugin?

### ISSUE THREAD

**Issue by seven1986** [esdoc/esdoc#340]
## **My project just like :**

```
src/
    code/ 
            news/
                    news.jsx
                    news-detail.jsx
            vendors/
                    ionic/
                    angular/
```
## **But when I config like this it does not work.**

```
{
  "source": "./src/code/",
  "destination": "./esdoc",
  "includes": [ "\\.(js|jsx)$" ],
  "excludes": ["^vendors"],
  "plugins": [
    { "name": "esdoc-es7-plugin" }
  ]
}

```

![image](https://cloud.githubusercontent.com/assets/20808494/19227551/1cfac3b0-8eee-11e6-984f-04fe7a787185.png)
## **So that I update (Publisher/Builder/DocBuilder.js ) this code, it works.**

![image](https://cloud.githubusercontent.com/assets/20808494/19227518/95d1b678-8eed-11e6-8023-e804af5d07ca.png)
# **I do not know the real reason,  But I wish you can help me solve this problem, thanks a lot :)**

**Comment by typhonrt** [comment]
Welcome to ESDoc @seven1986! I don't have enough info above per se to follow up, but I do want to point out that `esdoc-es7-plugin` is defunct / out of date and should not be used. The forthcoming v1.0 of ESDoc will be using Babylon for AST parsing and will fully parse ES6+ syntax. The current version does not and `esdoc-es7-plugin` isn't exactly a solution. 

As far as using `"excludes": ["^vendors"]` in the config file consider that it is a regex and using `^` will limit excluding paths `starting with` "vendors". It might not be doing what you think it may be doing. 

Now... As mentioned the forthcoming v1.0 of ESDoc will support Babylon for the AST generation / parsing and should support all modern syntax. In the meantime you might give my [current fork of esdoc](https://github.com/esdoc/esdoc/issues/292) a shot as it uses Babylon and may potentially not crash in your use case. If it does though let me know and I'll take a look, but you'll likely need to provide a bit more information for the error case that is raised.

**Comment by webOS101** [comment]
@typhonrt Your branch seems to have drifted away from `master` a bit.  If we want to test the latest ES6+ stuff, should we still use your branch?  I was not able to parse some ES7 features with `master`.

**Comment by webOS101** [comment]
Also, as an aside, is there someplace to chat with folks about esdoc?  (e.g. slack, irc, etc.)

**Comment by typhonrt** [comment]
@webOS101 my fork updated all dependencies and added Babylon support as of June advancing ESDoc at that time. The author / maintainer has made many changes sporadically to master since then, but nothing is released. More or less several of the changes on the master branch are refactoring type changes versus adding new functionality. Functionally my branch is still consistent in the generated output without failing with modern syntax (most likely). I guess you have to consider that the currently released version of ESDoc is way out of date where as my fork is updated compared to the available release on NPM. I'm not going to continue my fork once the official `v1.0` release is out as I did it in the first place as ESDoc was stalling for quite some time earlier in the year and to prove that using Babylon is a good direction for the future of ESDoc. In the meantime though it can help in certain situations and is more or less early exposure to using the latest Babylon release for AST parsing and modern syntax not causing things to fail outright. If things improve with my fork that is great and one should expect the official `v1.0` release to respond similarly or if there is a still a problem then it also needs to be vetted against the latest `v1.0` mainline release as well. 

As far as chatting goes.. I don't believe there is an official channel. I have a [Gitter channel](https://gitter.im/typhonjs/TyphonJS) for my efforts where I'd be glad to chat about ESDoc as it's a core part of some of the infrastructure I'm setting up w/ TyphonJS.

**Comment by h13i32maru** [comment]
@webOS101 Now, latest version of ESDoc is supports ECMAScript Proposal (aka ES7). Please check it.
https://esdoc.org/manual/usage/feature.html#ecmascript-proposal

I re-open this issue if is problem.

**Comment by webOS101** [comment]
@h13i32maru That's excellent news!  We already came up with a documentation system that works for us but I will do a quick verify in case we run into issues later.
