### ISSUE TITLE
ESParser: enable all Babylon plugins by default for next version of ESDoc.

### ISSUE THREAD

**Issue by typhonrt** [esdoc/esdoc#345]
@h13i32maru I just took a glance around the mainline code and saw that [ESParser](https://github.com/esdoc/esdoc/blob/master/src/Parser/ESParser.js) can be improved. For comparison please review the version of [ESParser](https://github.com/typhonjs-node-esdoc/esdoc/blob/master/src/Parser/ESParser.js) in my fork. 

In particular what I am concerned about is not enabling all Babylon plugins by default. There is no downside as far as I'm aware to enabling all plugins. There is also no reason to require the user to provide a config parameter `experimentalProposal` to enable just the `classProperties` plugin. To my knowledge there is only additional AST generated by the plugins and no detrimental effects for ESDoc processing when all are enabled by default. It's important for instance to have the `flow` plugin enabled so that AST processing by ESDoc plugins can pick up the additional Flow nodes even if ESDoc itself doesn't yet support Flow. So please consider enabling all Babylon plugins available by default.

A secondary concern is locking Babylon option `sourceType` to `module`. Please take a look how I use [a regex](https://github.com/typhonjs-node-esdoc/esdoc/blob/master/src/Parser/ESParser.js#L6) to determine if a file is using ES6 module format and select between `module` or `script` accordingly.

I'm certainly fine if you are interested in taking my version of ESParser over the current version. 

Also please update the ETA on v1.0 of ESDoc as things are seemingly stalling again.

**Comment by h13i32maru** [comment]
@typhonrt 

> There is also no reason to require the user to provide a config parameter experimentalProposal to enable just the classProperties plugin.

I have two reasons.
1. ESDoc supports ECMAScript standard. But `classProperties` is not standard yet. It is still proposal.

2. If `classProperties` is dropped from proposal, ESDoc will remove it from the implementation. At the time, ESDoc can display warning message for users that using it. Because `config.experimentalProposal.classProperties` is true.

The reason why `jsx` is default enabled is because I carelessly enabled it in the beginning.

> A secondary concern is locking Babylon option sourceType to module.

I will support that users can access babylon's options via a ESDoc plugin in future version. 

Thanks.

**Comment by h13i32maru** [comment]
https://github.com/esdoc/esdoc/issues/366

**Comment by typhonrt** [comment]
These aren't good solutions per se. By enabling all plugins it just outputs the AST. It's up to ESDoc later in the architecture to actually parse that AST to generate documentation. This prevents any plugins from potentially parsing that data. It's also not a good idea to add more configuration options of this sort especially a nested options `config_experimental_xxx`. Users will be confused in general. 

As far as 2 that is not likely to happen re: class properties being dropped. Once again displaying a warning for a needless configuration option is not good form. All of that should be transparent to the user and ESDoc architecture modified down stream to either support it or not. 

Little suggestions like this that get denied without really good justification / no debate add to the reasons why I feel a permanent fork is necessary of ESDoc.

**Comment by h13i32maru** [comment]
> It's up to ESDoc later in the architecture to actually parse that AST to generate documentation. 

Yes. So if a user changes parser options, it is the user's own responsibility. This is out of scope for ESDoc. In the first place, you can replace the parser.

> It's also not a good idea to add more configuration options of this sort especially a nested options config_experimental_xxx. Users will be confused in general.

This is your opinion.

> All of that should be transparent to the user and ESDoc architecture modified down stream to either support it or not.

If class properties is dropped, ESDoc fail parsing codes that using it. However ESDoc can suggest a reason of failing using `config.experimentalProposal`. Or ESDoc can be phased out of support it ("warning phase" -> "not support phase")

----

I do not want to discuss. Because I can correct problems and develop new functions using that time.(I spent 1 hour to that reading your comment and writing this comment) How I develop this software is my freedom. And I have no obligation to ask for discussion.

I am grateful that you reply to many issues from other users.
But if you think you need a fork, please do so. I have no right to stop it. However, that would be bad for the entire ecosystem. I think that it becomes a very big problem compared with trivial problems such as configuration file format and plugin implementation method.

Thank you for your understanding.

in Japanese:
私は議論がしたいわけではありません。なぜなら私はその時間を使って不具合を修正したり新しい機能を開発できます(あなたのコメントを読み、このコメントを書くのに1時間費やしました)。私がこのソフトをどう発展させるかは私の自由です。そして、私には議論をしなければならないという義務もありません。

あなたが他のユーザからの多くのissueに返信してくれたことには感謝しています。
しかし、あなたがフォークが必要とおもうなら、そうしてください。私にそれを止める権利はありません。ですが、それはエコシステム全体にとっては良くないことでしょう。設定ファイルの書式やプラグインの実装方式という些末な問題に比べて、非常に大きな問題になると思います。

ご理解ありがとう。

**Comment by h13i32maru** [comment]
https://twitter.com/h13i32maru/status/814657477417443328

**Comment by typhonrt** [comment]
Yes, configuration options are small in relation to the larger picture. They are engineering decisions though and your statement "If class properties is dropped, ESDoc fail parsing codes that using it." is equally just an opinion. With defensive engineering ESDoc could simply skip processing as the AST nodes will not be present for class properties thus no failure will occur. If parsing with Babylon fails then errors are exposed directly during that stage. 

I'm concerned that the path you have chosen of unilateral development inhibits ESDoc from what it can become. It's a matter of governance / stewardship for a project that is important for myself and an even larger potential community. The root problem is not being able to communicate effectively due to language issues and that is no ones fault. Beyond communication problems with potential collaborators this also leads to no one answering questions for the repo issues. 

I am keenly aware that doing a permanent fork is bad for the ecosystem and I would like to avoid it if at all possible. I have been quite patient in this regard, but I don't see another solution. One can relate this situation to the [Node.js and io.js fork](http://anandmanisankar.com/posts/nodejs-iojs-why-the-fork/) with the latter supporting open governance until those involved with Node.js (a single corporate entity at the time) modified Node.js to an open governance model. Only then did io.js rejoin Node.

Yes, it is your right and freedom to choose how develop ESDoc. These decisions though are not separate from any potential bad outcomes of a permanent fork.

Japanese:
はい、構成オプションは、大きな画像に比べて小さいです。彼らはエンジニアリング上の意思決定であり、あなたのステートメントは「クラスプロパティが破棄された場合、ESDocはそれを使用するコードの解析に失敗します。同様に単なる意見です。防御エンジニアリングでは、クラスのプロパティに対してASTノードが存在しないため、ESDocは処理をスキップすることができます。したがって、障害は発生しません。バビロンで解析するとエラーが発生すると、その段階で直接エラーが表示されます。

私は、あなたが一方的な開発を選択したことで、ESDocが何ができるのかを妨げているのではないかと心配しています。それは自分にとって重要なプロジェクトや、さらに大きな潜在的コミュニティにとってのガバナンス/スチュワードシップの問題です。根本的な問題は、言語の問題のために効果的にコミュニケーションを取ることができず、それは何の障害もありません。潜在的な共同作業者とのコミュニケーションの問題以外にも、これはレポの問題に関する質問に誰も答えないことにつながります。

恒久的なフォークを行うことは生態系にとって悪いことを痛感しており、可能な限り回避したいと考えています。私はこの点でかなり忍耐強く、しかし私は別の解決策を見ていません。この状況をNode.jsとio.jsのforkに関連付けることができます。これは、Node.js（当時の単一の企業エンティティ）がNode.jsをオープンガバナンスモデルに変更するまで、オープンガバナンスをサポートしていました。その後、io.jsがノードに再結合しました。

ESDocの開発方法を選択することは、あなたの権利と自由です。これらの決定は永続的なフォークの潜在的な悪い結果とは別個のものではありません。

**Comment by h13i32maru** [comment]
I am welcoming bug reports, feature requests, pull requests etc. But I will not be forced to state the reasons for discussion or refusal about them. I have no responsibility.

ESDoc is an individual project. I will continue to manage it personally. It will not be an organization. So do not compare with Node.js / io.js. In addition, the development stagnation of the case should have been a problem.

Please fork if you are dissatisfied with my idea. Or create again a new one. Just like I made ESDoc.

I am grateful for your work. But please do not take away my time, physical strength, mental more.

I will comment on this issue at the end. Do not reply to this issue if possible. I will not discuss it any more.

I am sorry that it became a strong word.

**Comment by typhonrt** [comment]
あなたはこれを読む必要はなく、それは私がその事柄について伝える最後のメッセージです / You don't have to read this and it's the last message I'll communicate on the matter.

I'm grateful for your work as I've [stated before](https://github.com/esdoc/esdoc/issues/292#issue-158773286). Just for the record though do consider again, **"I am welcoming** bug reports, feature requests, **pull requests** etc." This has not been the case at least from my perspective. Some of the larger potential PR efforts require discussion and even full proof of concept before they are submitted due to complexity or technical direction. An example of something you recently shutdown is #310. It's a significant waste of my time to work on a complex PR that will be rejected without discussion. 

The Node.js / io.js comparison is apt as a single entity controlled Node and contributors made a major fork over governance issues which is the same reason I'll likely be doing a permanent fork with ESDoc.

I hope you understand I'm not trying to take away your time, strength, or mental focus. There are not many folks that understand the entirety of the ESDoc architecture and I am one of the few if there are any others at all. 

I wish you well in all of your efforts, ESDoc and otherwise ([Jasper](https://jasperapp.io/), etc.) and hopefully a rift does not form between any permanent fork of ESDoc; I'll do my best to keep things compatible and integrate best of breed solutions you continue to develop.

**Comment by ratson** [comment]
@typhonrt After you create the fork, would you share the URL here? As I am looking for a fix / solution for https://github.com/esdoc/esdoc/issues/365

**Comment by h13i32maru** [comment]
I said that _Do not reply to this issue if possible._ . But you commented. So I have to lock this issue for my health.

> This has not been the case at least from my perspective.
> It's a significant waste of my time to work on a complex PR that will be rejected without discussion.

I welcome the pull request. But it is another matter to discuss or merge it. That is my freedom. You are also free to spend time on PR.

Even though Node.js had taken the policy of running in the community, stagnation of development was a problem due to the fact that it was not done. I am not saying that ESDoc will be managed in the community. OSS has various operating methods.

> I hope you understand I'm not trying to take away your time, strength, or mental focus.

I told you not to comment. But you commented on me so I am suffering again.

> Hopefully a rift does not form between any permanent fork of ESDoc

Fork is not the biggest problem for me. It is important that I can develop fun by myself.

Please do not torment me any more.
