### ISSUE TITLE
New feature regarding @private

### ISSUE THREAD

**Issue by mookraiser** [esdoc/esdoc#346]
It would be nice to have **@private** by default for all ES6 class methods, for instance in a React application, absolutely all methods of classes are private, so it is not handy to specify this tag every times.

**Comment by typhonrt** [comment]
Welcome to ESDoc @mookraiser!

The common naming convention in the Javascript world is to use a leading underscore to indicate that a method is private. IE. the following:
```
class MyClass {
   _myPrivateMethod() { ... }
}
```

ESDoc will mark all methods with leading underscores as automatically private. This is controlled by the `autoPrivate` [config parameter](https://esdoc.org/config.html) which defaults to true. Please note that also by default the `access` config parameter is set to `["public", "protected"]`, so for private methods to show up in documentation you need to change that to `["public", "protected", "private"]` in your configuration file.

Since this standard naming convention is supported for auto private methods already I highly doubt the ESDoc maintainer will change or add a feature for all methods to be automatically private as you suggest.

If this answers your question please consider closing this issue.

**Comment by mookraiser** [comment]
I'm aware of autoPrivate, but I was hoping something more configurable. It's the same story than jslint and eslint you know... let people do the way they want via conf.

**Comment by typhonrt** [comment]
Nope... ESDoc by default follows standard conventions. The answer is not ~~let people do the way they want via conf~~, but is actually let people do what they want via the plugin API. If you want to modify something like this which is custom for your use case create a plugin which modifies all document identifiers that are methods to private that don't have an explicit access annotation or whatever floats your boat. The "onHandleTag" plugin callback would look something like this:

```
export function onHandleTag(ev)
{
  for (let cntr = 0; cntr < ev.data.tag.length; cntr++)
  {
    const tag = ev.data.tag[cntr];
    if (tag.kind === 'method' && tag.access === null)
    {
      tag.access = 'private';
    }
  }
}
```

It should be noted that if a document identifier doesn't have an explicit access tag (`@access, @public, @protected, @private`) then `tag.access === null`; otherwise it's: public, protected, private.

Given that there is now a plugin solution available above consider closing this issue unless there is anything else pressing.

**Comment by mookraiser** [comment]
good lord, you are my saver :-)
I will do that, thanks !

**Comment by h13i32maru** [comment]
@typhonrt Thanks! Your reply is perfect. I also agree completely.

@mookraiser I hope it will work.
