### ISSUE TITLE
Using a named import for the class import statement

### ISSUE THREAD

**Issue by amirmohsen** [esdoc/esdoc#488]
I am using esdoc to produce documentation for my library. By default, esdoc generates an import statement at the top of each class doc that reads like this:

```js
import ClassName from 'package-name/path-to-class-name/ClassName';
```

I use rollup to bundle up my library which means these direct file imports are not valid when someone uses the library. Instead, they should be using named imports like:

```js
import {ClassName} from 'package-name';
```

I've read through the documentation and the issues, but haven't noticed any way of making this happen. Is this currently possible?

- OS type and version: Windows 10 64bit
- Node.js version: 8.5.0
- ESDoc version: 1.0.4

**Comment by MattMcFarland** [comment]
Hi @amirmohsen , you might be able to do this using the [esdoc-importpath-plugin](https://github.com/esdoc/esdoc-plugins/tree/master/esdoc-importpath-plugin) - it lets you use regular expressions to modify the imports.  

If this is about **imported exports** - I'm afraid this might not be possible, although if it is I would surely like to know too.  I call this "Directroy as a Module" or DAAM (pronounced damn xD),

**Comment by amirmohsen** [comment]
@MattMcFarland I took a look at that plugin but it only allows you to modify the path, not the import itself.  As I said, I need a named import not a default import. I might have to dig into the code of esdoc and see if I can create a plugin to address my issue if this is not already possible. This is essential for my library because as it stands, the import statement is just wrong and misleads the users once I publish the documentation.

**Comment by MattMcFarland** [comment]
@amirmohsen I hear ya.  

This project is really not being well maintained atm.  its a shame to be honest.  I'm currently working on another project because the owner of this one doesnt want any contributors, it's really in infancy but it aims to solve this.

TBH I think esdoc bends over backwards for `classes` and poorly represents `modules` - with docsense, I aim to have modules as first class citizens.

Have a look (here)[https://github.com/MattMcFarland/docsense].  Its currently in alpha right now so probably not something you want right away, but thought you should have it on your radar 👍

**Comment by amirmohsen** [comment]
@MattMcFarland thanks, I'll keep an eye out.

And I'll update the issue once I have a solution.

**Comment by amirmohsen** [comment]
Alright, I've put together a small plugin, [esdoc-named-import-plugin](https://www.npmjs.com/package/esdoc-named-import-plugin) that addresses this issue. It doesn't have any tests or accepts any options at the moment but does the basic transformation from a default import to a named import. If other people find the plugin useful, I might improve it over time. Closing this issue.
