### ISSUE TITLE
Note about your absence

### ISSUE THREAD

**Issue by pixelass** [esdoc/esdoc#504]
Please add a note about your absence.

If you have no time to develop, please allow more maintainers or at least add a note. Just answering to one of the many issues would help too.

Since you seem to be pushing in other repositories it seems like you simply ignore this project which is very sad. 

Yo spent a lot of time on esdoc and it would be nice to know what's going on or if anybody can be of any help.

Right now I'm not sure if it's safe to assume that this project is dead. If so please tell us so we can start looking for other options.

With the highest respect THANK YOU

**Comment by MattMcFarland** [comment]
This is why I created esdoc2 -> https://github.com/esdoc2/esdoc2 - because, if you see my post with the owner here: https://github.com/esdoc/esdoc/issues/480

1. He refuses to add contributors, and in my opinion, is breaking the TOS with Github, because he created an organization called "esdoc" but it is his "personal project" - 

2. THIS PROJECT IS DEAD - until he decides to commit to it, which given his history I would be surprised

3. He doesn't speak english, which makes things very hard to communicate with him

4. ESDOC2 - USE THAT PLEASE!  ESDOC2 is the contributor version, and is looking for contributors.  I know you have an issue on there, but I can't maintain esdoc2 myself.  I need help, and so if people could send me their npm logins, I will add them as contributors so they can publish to npm as well.

Thanks!!

**Comment by pixelass** [comment]
@MattMcFarland IMHO esdoc2 is not production ready. I opened several issues.

https://github.com/esdoc2/esdoc2-plugins/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc

I want to move away from esdoc ASAP but right now I don't see an option without doing a lot of adjustments in my project.
